#!/bin/sh

# set urxvt font size
sed -E /font/Is/[0-9]+/9/ -i ~/.Xresources
xrdb ~/.Xresources

# set i3 font size (windows and i3bar)
sed -E /Terminus/Is/10/9/ -i ~/.config/i3/config
i3-msg restart

# use hdmi audio ?? i guess
pactl set-card-profile 0 output:hdmi-stereo-extra1+input:analog-stereo
pactl set-default-sink alsa_output.pci-0000_00_1f.3.hdmi-stereo-extra1
